#+title: preview-tailor: Tailor AUCTeX preview scale to monitor/text scale
#+author: Paul Nelson

* Overview
The [[https://www.gnu.org/software/auctex/manual/preview-latex/preview-latex.html][preview]] feature of [[https://www.gnu.org/software/auctex/][AUCTeX]] provides live rendering of TeX code.  The rendering occurs at a user-specified preview scale.  The appropriate scale to use depends upon your monitor and your text scale.  This package makes the preview scale vary in a natural way with the text scale and the monitor.  In particular, it provides the command =M-x preview-tailor-set-multiplier= (and corresponding user option =preview-tailor-multipliers=) that allows you to adjust the preview scale for a given monitor.

* Configuration
Download this repository, install using =M-x package-install-file= (or package-vc-install, straight, elpaca, ...), and add something like the following to your [[https://www.emacswiki.org/emacs/InitFile][init file]]:
#+begin_src elisp
(use-package preview-tailor
  :after latex
  :config
  (preview-tailor-init))
#+end_src
The function =preview-tailor-init= sets the customization variable =preview-scale-function= to a function internal to this package that provides the calculation, so make sure you don't modify that variable elsewhere in your init file.

* Usage
This package calculates the preview scale by multiplying together four factors:

1. The result of =preview-scale-from-face=.
2. The current text scale factor (as tweaked via the =text-scale-adjust= commands bound by default to =C-x C-+= and =C-x C--=)
3. A multiplier determined by the current frame's monitor attributes, with default value 1.
4. An additional factor provided by the user customization =preview-tailor-additional-factor-function= (which defaults to nil, which means to omit this factor).
5. The buffer-local variable =preview-tailor-local-multiplier= (which defaults to 1).

To adjust the multiplier for a given monitor, use =M-x preview-tailor-set-multiplier=.  This adjusts the customization variable =preview-tailor-multipliers=, which is an association list mapping lists of monitor attributes to numbers.  The multiplier is calculated by finding the first entry in the list all of whose attributes match the current ones.

* Saving your settings
The package stores your monitor-specific settings in the dotfile ".preview-tailor" inside your user-emacs-directory.  This allows you to keep your settings separate from your init file, making it easier to sync your Emacs configuration across different computers.

To save your multipliers for future sessions, use =M-x preview-tailor-save=.  The package will automatically load the settings from the dotfile when initialized.  To make saving automatic, you can add the following to your init file:

#+begin_src elisp
(add-hook 'kill-emacs-hook #'preview-tailor-save)
#+end_src

If you prefer to edit the dotfile directly, the function =preview-tailor-load= might be come in handy -- it loads the settings from the dotfile into the variable =preview-tailor-multipliers=.
